//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMap.NET.WindowsForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BMap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BMap.NET.WindowsForm.Properties.BMap", typeof(BMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国|1||0
        ///黑龙江省|2|1|1
        ///大兴安岭地区|38|2|2
        ///黑河市|39|2|2
        ///伊春市|40|2|2
        ///齐齐哈尔市|41|2|2
        ///佳木斯市|42|2|2
        ///鹤岗市|43|2|2
        ///绥化市|44|2|2
        ///双鸭山市|45|2|2
        ///鸡西市|46|2|2
        ///七台河市|47|2|2
        ///哈尔滨市|48|2|2
        ///牡丹江市|49|2|2
        ///大庆市|50|2|2
        ///甘肃省|6|1|1
        ///嘉峪关市|33|6|2
        ///金昌市|34|6|2
        ///白银市|35|6|2
        ///兰州市|36|6|2
        ///酒泉市|37|6|2
        ///张掖市|117|6|2
        ///武威市|118|6|2
        ///庆阳市|135|6|2
        ///定西市|136|6|2
        ///临夏回族自治州|182|6|2
        ///天水市|196|6|2
        ///甘南藏族自治州|247|6|2
        ///陇南市|256|6|2
        ///平凉市|359|6|2
        ///广东省|7|1|1
        ///东莞市|119|7|2
        ///东沙群岛|120|7|2
        ///韶关市|137|7|2
        ///佛山市|138|7|2
        ///茂名市|139|7|2
        ///珠海市|140|7|2
        ///梅州市|141|7|2
        ///中山市|187|7|2
        ///清远市|197|7|2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baidu_citys {
            get {
                return ResourceManager.GetString("baidu_citys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_close {
            get {
                object obj = ResourceManager.GetObject("ico_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_search {
            get {
                object obj = ResourceManager.GetObject("ico_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
